# Generated by Django 5.1.7 on 2025-04-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='descount',
            new_name='discount',
        ),
    ]
